version: '3.1'

services:
  java9-test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: java9-test
    ports:
      - "8081:8081"
    expose:
      - "8081"
    container_name: java9-test